### ISSUE TITLE
I need documentation for this code, can you please provide it if you have

### ISSUE THREAD

**Issue by rafeya087** [pervasive-computing-systems-group/DroNS3#16]
I didn't find its documentation, i want to understand this project, can you please tell where i can  look for its documentation of the code

**Comment by JonD07** [comment]
Documentation on how the code works can be found in the "_DroNS-3: Framework for Realistic Drone and Networking Simulators_" publication: https://dl.acm.org/doi/pdf/10.1145/3597060.3597239.

Steps for getting the project to run are found in the project Wiki here on Github.
